const userController = require('../controllers/userController')
const productController = require('../controllers/productController')
const imageController = require('../controllers/imageController.js')
const multer = require('multer');
const storage = multer.memoryStorage()
const upload = multer({storage: storage})
const router = require('express').Router()
router.get('/healthz', userController.getStatus)
router.post('/v1/user', userController.addUser)
router.get('/v1/user/:id', userController.getUser)
router.put('/v1/user/:id', userController.updateUser)
router.post('/v1/product',productController.addProduct)
router.get('/v1/product/:id',productController.getProduct)
router.delete('/v1/product/:id',productController.deleteProduct)
router.put('/v1/product/:id',productController.updateProduct)
router.patch('/v1/product/:id',productController.patchProduct)
router.get('/v1/product/:id/image', imageController.getAllImages)
router.post('/v1/product/:id/image',upload.single('image'), imageController.uploadImage)
router.get('/v1/product/:id/image/:image', imageController.getImage)
router.delete('/v1/product/:id/image/:image', imageController.deleteImage)
router.get('/northeastern', userController.getNortheastern)
module.exports = router
